global using Common;
global using static Common.Prelube;
global using FluentValidation;
global using LanguageExt;
global using LanguageExt.Common;
global using static LanguageExt.Prelude;
global using LanguageExt.Effects;
global using LanguageExt.Pipes;
global using LanguageExt.Pretty;
global using static ProductApi.Tests.Functions;