apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: product-binding
spec:
  type: bindings.postgresql
  version: v1
  metadata:
    - name: connectionString
      value: >-
        host=localhost
        port=5432
        database=petal-box
        user=postgres
        password=P@ssw0rd
    - name: direction
      value: input, output
