CREATE TABLE IF NOT EXISTS customer (
    id CHARACTER VARYING(36) PRIMARY KEY,
    user_id CHARACTER VARYING(36) NOT NULL,
    first_name CHARACTER VARYING(100) NOT NULL,
    last_name CHARACTER VARYING(100) NOT NULL,
    email CHARACTER VARYING(255) NOT NULL,
    phone CHARACTER VARYING(20)
);

CREATE TABLE IF NOT EXISTS address (
    id CHARACTER VARYING(36) PRIMARY KEY,
    customer_id CHARACTER VARYING(36) REFERENCES customer(id) ON DELETE CASCADE,
    user_id CHARACTER VARYING(36) NOT NULL,
    address_name CHARACTER VARYING(100) NOT NULL,
    address_text CHARACTER VARYING(500) NOT NULL,
    phone CHARACTER VARYING(20) NOT NULL,
	is_default BOOLEAN DEFAULT false
);
