CREATE TABLE IF NOT EXISTS sale_order (
    id CHARACTER VARYING(36) PRIMARY KEY,
    user_id CHARACTER VARYING(36) NOT NULL,
    customer_id CHARACTER VARYING(36) NOT NULL,
    order_at TIMESTAMPTZ NOT NULL,
    status INT NOT NULL,
    order_total DECIMAL(14, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS sale_order_line (
    id CHARACTER VARYING(36) PRIMARY KEY,
    sale_order_id CHARACTER VARYING(36) REFERENCES sale_order(id) ON DELETE CASCADE,
    user_id CHARACTER VARYING(36) NOT NULL,
    customer_id CHARACTER VARYING(36) NOT NULL,
    product_id CHARACTER VARYING(36) NOT NULL,
    name CHARACTER VARYING(255) NOT NULL,
    quantity INT NOT NULL,
    price DECIMAL(9, 2) NOT NULL
);
